#!/bin/sh

# Note: The javascript is generated by the
# package.json before calling this script.  

mkdir -p dist #ensure there's a folder 

#copy styles
cp -v src/app/style.css dist/
cp -v node_modules/material-design-lite/dist/material.css dist/
cp -v node_modules/material-design-lite/dist/material.js dist/

#copy html menu
cp -v src/app/menu/menu.tpl.html dist/

#copy plugin specifics
cp -v src/plugin-specific/* dist/
