#!/bin/sh

# Note: The javascript is generated by the
# package.json before calling this script.  

#copy styles
cp -v src/app/style.css dist/

#copy html menu
cp -v src/app/menu/menu.tpl.html dist/

#copy plugin specifics
cp -v src/plugin-specific/* dist/
